#include <iostream>
#include <cstdlib>
#include "SmallCoverGraph.h"

using namespace std;

SmallCoverGraph::SmallCoverGraph(unsigned vertexCount, float edgeProba, unsigned coverSize): SimpleGraph(coverSize, edgeProba) {

	cout << "Size VC_In :" << getVertexCount() << endl;
	verticesInVC = getVertices();
	for(unsigned i = 0; i < (vertexCount - coverSize); i++)
		verticesOutOfVC.insert(addVertex());

	/* 	srand is a pseudo-random number generator which is initialised by a seed
	 *	for every seed srand generates a different succesion of results
	 *	the value generated by the function time changes every second, that's why
	 *	it is a good aproach for most randoming needs
	 */
	srand((unsigned)time(0));

	set<int>::iterator it1;
	set<int>::iterator it2;
	for(it1 = verticesOutOfVC.begin(); it1 != verticesOutOfVC.end(); it1++)
		for(it2 = verticesInVC.begin(); it2 != verticesInVC.end(); it2++) {
			if (rand() % 100 < probability)
				addEdge(*it1,*it2);
		}

	cout << "Vertices out of vertex cover" << endl;
	for(set<int>::iterator it = verticesOutOfVC.begin(); it != verticesOutOfVC.end(); it++) {
		cout << "" << *it << " , ";
	}
	cout << endl;

	cout << "Vertices in vertex cover" << endl;
		for(set<int>::iterator it2 = verticesInVC.begin(); it2 != verticesInVC.end(); it2++) {
			cout << "" << *it2 << " , " ;
		}
	cout << endl << "End of set !" << endl << endl;
}

SmallCoverGraph::~SmallCoverGraph() {
	// TODO Auto-generated destructor stub
}
